AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
    systemDB:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: system
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

    videosController:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: VideosController/
            Handler: videos.handle
            Runtime: python3.8
            Events:
                videosApiEventDefault:
                    Type: Api
                    Properties:
                        Path: /videos
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
                videosApiEventProxy:
                    Type: Api
                    Properties:
                        Path: /videos/{proxy+}
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
            Policies:
                DynamoDBCrudPolicy:
                    TableName: !Ref systemDB
    
    playlistsController:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: PlaylistsController/
            Handler: playlists.handle
            Runtime: python3.8
            Events:
                videosApiEventDefault:
                    Type: Api
                    Properties:
                        Path: /playlists
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
                videosApiEventProxy:
                    Type: Api
                    Properties:
                        Path: /playlists/{proxy+}
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
            Policies:
                DynamoDBCrudPolicy:
                    TableName: !Ref systemDB


    userVotesController:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: UsersController/
            Handler: votes.handle
            Runtime: python3.8
            Events:
                userVotes:
                    Type: Api
                    Properties:
                        Path: /users/votes
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref systemDB

    usersController:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: UsersController/
            Handler: users.handle
            Runtime: python3.8
            Events:
                videosApiEventDefault:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
                videosApiEventProxy:
                    Type: Api
                    Properties:
                        Path: /users/{proxy+}
                        Method: ANY
                        Auth:
                            Authorizer: globalApiAuth
            Policies:
                DynamoDBCrudPolicy:
                    TableName: !Ref systemDB

Globals:
    Api:
        Auth:
            Authorizers:
                globalApiAuth:
                    UserPoolArn: arn:aws:cognito-idp:us-west-2:580314847820:userpool/us-west-2_3LjdLzhH5
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
